# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/proto/conversation/v1alpha/context.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/cloud/proto/conversation/v1alpha/context.proto',
  package='google.cloud.conversation.v1alpha',
  syntax='proto3',
  serialized_pb=_b('\n5google/cloud/proto/conversation/v1alpha/context.proto\x12!google.cloud.conversation.v1alpha\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\\\n\x07\x43ontext\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0elifespan_count\x18\x02 \x01(\x05\x12+\n\nparameters\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"%\n\x13ListContextsRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\"T\n\x14ListContextsResponse\x12<\n\x08\x63ontexts\x18\x01 \x03(\x0b\x32*.google.cloud.conversation.v1alpha.Context\"!\n\x11GetContextRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"c\n\x14\x43reateContextRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\x12;\n\x07\x63ontext\x18\x02 \x01(\x0b\x32*.google.cloud.conversation.v1alpha.Context\"S\n\x14UpdateContextRequest\x12;\n\x07\x63ontext\x18\x01 \x01(\x0b\x32*.google.cloud.conversation.v1alpha.Context\"$\n\x14\x44\x65leteContextRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"j\n\x1a\x42\x61tchCreateContextsRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\x12<\n\x08\x63ontexts\x18\x02 \x03(\x0b\x32*.google.cloud.conversation.v1alpha.Context\"[\n\x1b\x42\x61tchCreateContextsResponse\x12<\n\x08\x63ontexts\x18\x01 \x03(\x0b\x32*.google.cloud.conversation.v1alpha.Context\"*\n\x18\x44\x65leteAllContextsRequest\x12\x0e\n\x06parent\x18\x01 \x01(\tB\x89\x01\n%com.google.cloud.conversation.v1alphaB\x0c\x43ontextProtoP\x01ZMgoogle.golang.org/genproto/googleapis/cloud/conversation/v1alpha;conversation\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTEXT = _descriptor.Descriptor(
  name='Context',
  full_name='google.cloud.conversation.v1alpha.Context',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.conversation.v1alpha.Context.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lifespan_count', full_name='google.cloud.conversation.v1alpha.Context.lifespan_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='google.cloud.conversation.v1alpha.Context.parameters', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=244,
)


_LISTCONTEXTSREQUEST = _descriptor.Descriptor(
  name='ListContextsRequest',
  full_name='google.cloud.conversation.v1alpha.ListContextsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='google.cloud.conversation.v1alpha.ListContextsRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=283,
)


_LISTCONTEXTSRESPONSE = _descriptor.Descriptor(
  name='ListContextsResponse',
  full_name='google.cloud.conversation.v1alpha.ListContextsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contexts', full_name='google.cloud.conversation.v1alpha.ListContextsResponse.contexts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=369,
)


_GETCONTEXTREQUEST = _descriptor.Descriptor(
  name='GetContextRequest',
  full_name='google.cloud.conversation.v1alpha.GetContextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.conversation.v1alpha.GetContextRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=404,
)


_CREATECONTEXTREQUEST = _descriptor.Descriptor(
  name='CreateContextRequest',
  full_name='google.cloud.conversation.v1alpha.CreateContextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='google.cloud.conversation.v1alpha.CreateContextRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='google.cloud.conversation.v1alpha.CreateContextRequest.context', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=505,
)


_UPDATECONTEXTREQUEST = _descriptor.Descriptor(
  name='UpdateContextRequest',
  full_name='google.cloud.conversation.v1alpha.UpdateContextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='google.cloud.conversation.v1alpha.UpdateContextRequest.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=590,
)


_DELETECONTEXTREQUEST = _descriptor.Descriptor(
  name='DeleteContextRequest',
  full_name='google.cloud.conversation.v1alpha.DeleteContextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.cloud.conversation.v1alpha.DeleteContextRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=628,
)


_BATCHCREATECONTEXTSREQUEST = _descriptor.Descriptor(
  name='BatchCreateContextsRequest',
  full_name='google.cloud.conversation.v1alpha.BatchCreateContextsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='google.cloud.conversation.v1alpha.BatchCreateContextsRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contexts', full_name='google.cloud.conversation.v1alpha.BatchCreateContextsRequest.contexts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=630,
  serialized_end=736,
)


_BATCHCREATECONTEXTSRESPONSE = _descriptor.Descriptor(
  name='BatchCreateContextsResponse',
  full_name='google.cloud.conversation.v1alpha.BatchCreateContextsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contexts', full_name='google.cloud.conversation.v1alpha.BatchCreateContextsResponse.contexts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=738,
  serialized_end=829,
)


_DELETEALLCONTEXTSREQUEST = _descriptor.Descriptor(
  name='DeleteAllContextsRequest',
  full_name='google.cloud.conversation.v1alpha.DeleteAllContextsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='google.cloud.conversation.v1alpha.DeleteAllContextsRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=831,
  serialized_end=873,
)

_CONTEXT.fields_by_name['parameters'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_LISTCONTEXTSRESPONSE.fields_by_name['contexts'].message_type = _CONTEXT
_CREATECONTEXTREQUEST.fields_by_name['context'].message_type = _CONTEXT
_UPDATECONTEXTREQUEST.fields_by_name['context'].message_type = _CONTEXT
_BATCHCREATECONTEXTSREQUEST.fields_by_name['contexts'].message_type = _CONTEXT
_BATCHCREATECONTEXTSRESPONSE.fields_by_name['contexts'].message_type = _CONTEXT
DESCRIPTOR.message_types_by_name['Context'] = _CONTEXT
DESCRIPTOR.message_types_by_name['ListContextsRequest'] = _LISTCONTEXTSREQUEST
DESCRIPTOR.message_types_by_name['ListContextsResponse'] = _LISTCONTEXTSRESPONSE
DESCRIPTOR.message_types_by_name['GetContextRequest'] = _GETCONTEXTREQUEST
DESCRIPTOR.message_types_by_name['CreateContextRequest'] = _CREATECONTEXTREQUEST
DESCRIPTOR.message_types_by_name['UpdateContextRequest'] = _UPDATECONTEXTREQUEST
DESCRIPTOR.message_types_by_name['DeleteContextRequest'] = _DELETECONTEXTREQUEST
DESCRIPTOR.message_types_by_name['BatchCreateContextsRequest'] = _BATCHCREATECONTEXTSREQUEST
DESCRIPTOR.message_types_by_name['BatchCreateContextsResponse'] = _BATCHCREATECONTEXTSRESPONSE
DESCRIPTOR.message_types_by_name['DeleteAllContextsRequest'] = _DELETEALLCONTEXTSREQUEST

Context = _reflection.GeneratedProtocolMessageType('Context', (_message.Message,), dict(
  DESCRIPTOR = _CONTEXT,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.Context)
  ))
_sym_db.RegisterMessage(Context)

ListContextsRequest = _reflection.GeneratedProtocolMessageType('ListContextsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONTEXTSREQUEST,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.ListContextsRequest)
  ))
_sym_db.RegisterMessage(ListContextsRequest)

ListContextsResponse = _reflection.GeneratedProtocolMessageType('ListContextsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONTEXTSRESPONSE,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.ListContextsResponse)
  ))
_sym_db.RegisterMessage(ListContextsResponse)

GetContextRequest = _reflection.GeneratedProtocolMessageType('GetContextRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCONTEXTREQUEST,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.GetContextRequest)
  ))
_sym_db.RegisterMessage(GetContextRequest)

CreateContextRequest = _reflection.GeneratedProtocolMessageType('CreateContextRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATECONTEXTREQUEST,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.CreateContextRequest)
  ))
_sym_db.RegisterMessage(CreateContextRequest)

UpdateContextRequest = _reflection.GeneratedProtocolMessageType('UpdateContextRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATECONTEXTREQUEST,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.UpdateContextRequest)
  ))
_sym_db.RegisterMessage(UpdateContextRequest)

DeleteContextRequest = _reflection.GeneratedProtocolMessageType('DeleteContextRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETECONTEXTREQUEST,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.DeleteContextRequest)
  ))
_sym_db.RegisterMessage(DeleteContextRequest)

BatchCreateContextsRequest = _reflection.GeneratedProtocolMessageType('BatchCreateContextsRequest', (_message.Message,), dict(
  DESCRIPTOR = _BATCHCREATECONTEXTSREQUEST,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.BatchCreateContextsRequest)
  ))
_sym_db.RegisterMessage(BatchCreateContextsRequest)

BatchCreateContextsResponse = _reflection.GeneratedProtocolMessageType('BatchCreateContextsResponse', (_message.Message,), dict(
  DESCRIPTOR = _BATCHCREATECONTEXTSRESPONSE,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.BatchCreateContextsResponse)
  ))
_sym_db.RegisterMessage(BatchCreateContextsResponse)

DeleteAllContextsRequest = _reflection.GeneratedProtocolMessageType('DeleteAllContextsRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEALLCONTEXTSREQUEST,
  __module__ = 'google.cloud.proto.conversation.v1alpha.context_pb2'
  # @@protoc_insertion_point(class_scope:google.cloud.conversation.v1alpha.DeleteAllContextsRequest)
  ))
_sym_db.RegisterMessage(DeleteAllContextsRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n%com.google.cloud.conversation.v1alphaB\014ContextProtoP\001ZMgoogle.golang.org/genproto/googleapis/cloud/conversation/v1alpha;conversation\370\001\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
